/*
	Generated by KBEngine!
	Please do not modify this file!
	
	tools = kbcmd
*/

#pragma once

#include "KBECommon.h"
#include "EntityCall.h"
#include "KBETypes.h"
#include "CustomDataTypes.h"


// defined in */scripts/entity_defs/Avatar.def

namespace KBEngine
{

class KBENGINEPLUGINS_API EntityBaseEntityCall_AvatarBase : public EntityCall
{
public:

	EntityBaseEntityCall_AvatarBase(int32 eid, const FString& ename);

	virtual ~EntityBaseEntityCall_AvatarBase();
};

class KBENGINEPLUGINS_API EntityCellEntityCall_AvatarBase : public EntityCall
{
public:

	EntityCellEntityCall_AvatarBase(int32 eid, const FString& ename);

	virtual ~EntityCellEntityCall_AvatarBase();
};

}