/*
	Generated by KBEngine!
	Please do not modify this file!
	
	tools = kbcmd
*/

#pragma once

#include "KBECommon.h"
#include "EntityCall.h"
#include "KBETypes.h"
#include "CustomDataTypes.h"


// defined in */scripts/entity_defs/FirstSpace.def

namespace KBEngine
{

class KBENGINEPLUGINS_API EntityBaseEntityCall_FirstSpaceBase : public EntityCall
{
public:

	EntityBaseEntityCall_FirstSpaceBase(int32 eid, const FString& ename);

	virtual ~EntityBaseEntityCall_FirstSpaceBase();
};

class KBENGINEPLUGINS_API EntityCellEntityCall_FirstSpaceBase : public EntityCall
{
public:

	EntityCellEntityCall_FirstSpaceBase(int32 eid, const FString& ename);

	virtual ~EntityCellEntityCall_FirstSpaceBase();
};

}