/*
	Generated by KBEngine!
	Please do not modify this file!
	Please inherit this module, such as: (class FirstEntity : public FirstEntityBase)
	tools = kbcmd
*/

#pragma once
#include "KBECommon.h"
#include "Entity.h"
#include "KBETypes.h"
#include "EntityCallFirstEntityBase.h"

namespace KBEngine
{

class Method;
class Property;
class MemoryStream;

// defined in */scripts/entity_defs/FirstEntity.def
	// Please inherit and implement "class FirstEntity : public FirstEntityBase"
class KBENGINEPLUGINS_API FirstEntityBase : public Entity
{
public:
	EntityBaseEntityCall_FirstEntityBase* pBaseEntityCall;
	EntityCellEntityCall_FirstEntityBase* pCellEntityCall;


	virtual void OnEnter() = 0; 
	virtual void OnSay(const FString& arg1) = 0; 

	void onComponentsEnterworld() override;
	void onComponentsLeaveworld() override;

	void onGetBase() override;
	void onGetCell() override;
	void onLoseCell() override;

	EntityCall* getBaseEntityCall() override;
	EntityCall* getCellEntityCall() override;


	void onRemoteMethodCall(MemoryStream& stream) override;
	void onUpdatePropertys(MemoryStream& stream) override;
	void callPropertysSetMethods() override;

	FirstEntityBase();
	virtual ~FirstEntityBase();

	void attachComponents() override;
	void detachComponents() override;

};

}