/*
	Generated by KBEngine!
	Please do not modify this file!
	Please inherit this module, such as: (class FirstSpace : public FirstSpaceBase)
	tools = kbcmd
*/

#pragma once
#include "KBECommon.h"
#include "Entity.h"
#include "KBETypes.h"
#include "EntityCallFirstSpaceBase.h"

namespace KBEngine
{

class Method;
class Property;
class MemoryStream;

// defined in */scripts/entity_defs/FirstSpace.def
	// Please inherit and implement "class FirstSpace : public FirstSpaceBase"
class KBENGINEPLUGINS_API FirstSpaceBase : public Entity
{
public:
	EntityBaseEntityCall_FirstSpaceBase* pBaseEntityCall;
	EntityCellEntityCall_FirstSpaceBase* pCellEntityCall;



	void onComponentsEnterworld() override;
	void onComponentsLeaveworld() override;

	void onGetBase() override;
	void onGetCell() override;
	void onLoseCell() override;

	EntityCall* getBaseEntityCall() override;
	EntityCall* getCellEntityCall() override;


	void onRemoteMethodCall(MemoryStream& stream) override;
	void onUpdatePropertys(MemoryStream& stream) override;
	void callPropertysSetMethods() override;

	FirstSpaceBase();
	virtual ~FirstSpaceBase();

	void attachComponents() override;
	void detachComponents() override;

};

}